version: '3.8'

services:
  backend:
    build: .
    container_name: backend-dinochomp
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/dinochompdb
      SPRING_DATA_MONGODB_DATABASE: dinochompdb
    depends_on:
      - mongo
    networks:
      - dinochomp-net

  mongo:
    image: mongo:7.0
    container_name: mongo-dinochomp
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    networks:
      - dinochomp-net

volumes:
  mongodata:

networks:
  dinochomp-net: